import { CalendarDays, ChevronRight, CreditCard, Pencil } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Badge, Empty, Field, Loading, Modal } from '../../components/UI'
import { roomlyApi } from '../../lib/roomlyApi'
import type { Booking } from '../../types'
import { bookingStatusName, date, money, paymentStatusName } from '../../types'
import { fail, heading, statusTone } from './shared'

export function BookingPanel(){
  const [items,setItems]=useState<Booking[]>([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Booking>();const [mode,setMode]=useState<'pay'|'edit'>();const [methods,setMethods]=useState<Array<{id:number;nameEn?:string;name?:string}>>([]);const [method,setMethod]=useState(1);const [dates,setDates]=useState({startDate:'',endDate:''})
  const load=()=>roomlyApi.bookings.mine().then(setItems).catch(fail).finally(()=>setLoading(false));useEffect(()=>{void load();void roomlyApi.payments.methods().then(setMethods).catch(()=>{})},[])
  const open=(booking:Booking,next:'pay'|'edit')=>{setSelected(booking);setMode(next);setDates({startDate:booking.checkInDate.slice(0,10),endDate:booking.checkOutDate.slice(0,10)})}
  const cancel=async(id:string)=>{if(!confirm('Bạn chắc chắn muốn hủy đặt phòng?'))return;try{await roomlyApi.bookings.cancel(id);toast.success('Đã hủy đặt phòng');load()}catch(e){fail(e)}}
  const saveDates=async()=>{if(!selected)return;try{await roomlyApi.bookings.update(selected.bookingId,{bookingId:selected.bookingId,userId:selected.guestId,roomId:selected.room.id,startDate:new Date(dates.startDate).toISOString(),endDate:new Date(dates.endDate).toISOString()});toast.success('Đã cập nhật ngày lưu trú');setMode(undefined);load()}catch(e){fail(e)}}
  const pay=async()=>{if(!selected)return;try{const returnUrl=location.origin+'/dashboard/bookings';const result=await roomlyApi.bookings.pay(selected.bookingId,method,{onSuccess:returnUrl,onFailure:returnUrl,onPending:returnUrl});toast.success('Đã tạo phiên thanh toán');if(result.checkoutMethod==='POST'&&result.paymentUrl){const form=document.createElement('form');form.method='POST';form.action=result.paymentUrl;Object.entries(result.checkoutFields||{}).forEach(([name,value])=>{const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.appendChild(input)});document.body.appendChild(form);form.submit()}else if(result.paymentUrl)location.assign(result.paymentUrl)}catch(e){fail(e)}}
  const refund=async(id:string)=>{try{await roomlyApi.payments.refund(id);toast.success('Đã xử lý hoàn tiền');load()}catch(e){fail(e)}}
  return <>{heading('Chuyến đi của tôi','Theo dõi, chỉnh sửa, thanh toán và hủy các đặt phòng.')}{loading?<Loading/>:items.length?<div className="booking-list">{items.map(b=>{const bookingName=bookingStatusName(b.status);const paymentName=paymentStatusName(b.paymentStatus);const closed=/Hoàn tất|hủy|từ chối|hết hạn/i.test(bookingName);return <article className="panel-card booking-row" key={b.bookingId}><div className="booking-thumb">{b.roomled?null:b.room?.photos?.[0]?.url&&<img src={b.room.photos[0].url} alt=""/>}</div><div className="booking-main"><div><Badge tone={statusTone(bookingName)}>{bookingName}</Badge> <Badge tone={statusTone(paymentName)}>{paymentName}</Badge></div><h3>{b.room?.title||'Phòng đã đặt'}</h3><p><CalendarDays/> {date(b.checkInDate)} — {date(b.checkOutDate)}</p><strong>{money(b.totalPrice)}</strong></div><div className="row-actions">{/Chờ thanh toán/i.test(bookingName)&&<button className="btn small" onClick={()=>open(b,'pay')}><CreditCard/> Thanh toán</button>}{!closed&&<button className="outline-btn" onClick={()=>open(b,'edit')}><Pencil/> Đổi ngày</button>}{!closed&&<button className="outline-btn danger" onClick={()=>cancel(b.bookingId)}>Hủy</button>}{/Đã thanh toán/i.test(paymentName)&&<button className="text-btn" onClick={()=>refund(b.bookingId)}>Hoàn tiền</button>}<a className="text-btn" href={`/rooms/${b.room?.id}`}>Xem phòng <ChevronRight/></a></div></article>})}</div>:<Empty title="Bạn chưa có chuyến đi nào" text="Hãy khám phá một nơi ở mới."/>}
    {selected&&mode==='pay'&&<Modal title="Thanh toán đặt phòng" onClose={()=>setMode(undefined)}><div className="modal-form"><h2>{money(selected.totalPrice)}</h2><Field label="Phương thức thanh toán"><select value={method} onChange={e=>setMethod(Number(e.target.value))}>{methods.length?methods.map(m=><option key={m.id} value={m.id}>{m.name||m.nameEn||`Phương thức ${m.id}`}</option>):<><option value="1">Ví Roomly</option><option value="2">Thẻ</option><option value="5">Chuyển khoản</option></>}</select></Field><button className="btn full" onClick={pay}>Tiếp tục thanh toán</button></div></Modal>}
    {selected&&mode==='edit'&&<Modal title="Thay đổi ngày lưu trú" onClose={()=>setMode(undefined)}><div className="modal-form"><Field label="Nhận phòng"><input type="date" value={dates.startDate} onChange={e=>setDates({...dates,startDate:e.target.value})}/></Field><Field label="Trả phòng"><input type="date" min={dates.startDate} value={dates.endDate} onChange={e=>setDates({...dates,endDate:e.target.value})}/></Field><button className="btn full" onClick={saveDates}>Lưu thay đổi</button></div></Modal>}</>
}
